version: "2"
services:
  nginx:
    image: nginx
    volumes_from:
      - phpfpm
    volumes:
      - ./misc/nginx-conf:/etc/nginx
      - ./misc/nginx-log:/var/log/nginx
    ports:
      - "8080:80"
  phpfpm:
    image: registry.cn-hangzhou.aliyuncs.com/reminz/php:5.6-fpm-root
    volumes:
      - ./src:/var/www/html
      - ./misc/php-conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./misc/php-conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
    - APP_ENV=develop
    - APP_DEBUG="true"
    - DB_CONNECTION=mysql
    - DB_HOST=db
    - DB_PORT=3306
    - DB_DATABASE=sampleapp
    - DB_USERNAME=root
    - DB_PASSWORD=root
  db:
    image: mysql:5.6
    restart: always
    volumes:
      - ./misc/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"