version: "2"
services:
  nginx:
    image: nginx
    volumes_from:
      - phpfpm
    volumes:
      - ./misc/nginx-conf:/etc/nginx
      - ./misc/nginx-log:/var/log/nginx
    ports:
      - "8080:80"
  phpfpm:
    image: registry.cn-hangzhou.aliyuncs.com/reminz/php:5.6-fpm-root
    volumes:
      - ./src:/var/www/html
      - ./misc/php-conf/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./misc/php-conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
    - APP_ENV=develop
    - APP_DEBUG="true"